font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
font_size        11.0

foreground       #CB8E37
background       #1C160E
cursor           #A4793F
cursor_shape     beam

selection_foreground #1C160E
selection_background #CB8E37

color0  #1C160E
color1  #93662E
color2  #A4793F
color3  #CB8E37
color4  #4A3723
color5  #694C2C
color6  #795F40
color7  #CB8E37
color8  #4A3723
color9  #93662E
color10 #A4793F
color11 #CB8E37
color12 #694C2C
color13 #795F40
color14 #93662E
color15 #CB8E37

window_padding_width 10
background_opacity   0.93
