font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
font_size        11.0

foreground       #EBC9AA
background       #0E0F16
cursor           #EAAF62
cursor_shape     beam

selection_foreground #0E0F16
selection_background #EAAF62

color0  #0E0F16
color1  #AE5F3C
color2  #96689F
color3  #EAAF62
color4  #402E55
color5  #684890
color6  #96689F
color7  #EBC9AA
color8  #402E55
color9  #AE5F3C
color10 #96689F
color11 #EAAF62
color12 #684890
color13 #96689F
color14 #AE5F3C
color15 #EBC9AA

window_padding_width 12
background_opacity   0.90
