font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
font_size        11.0

foreground       #EB946D
background       #240E0A
cursor           #D36C61
cursor_shape     beam

selection_foreground #240E0A
selection_background #D36C61

color0  #240E0A
color1  #D36C61
color2  #A25560
color3  #EB946D
color4  #6C3C52
color5  #B0788A
color6  #924B37
color7  #EB946D
color8  #592A24
color9  #D36C61
color10 #A25560
color11 #EB946D
color12 #6C3C52
color13 #B0788A
color14 #924B37
color15 #EB946D

window_padding_width 12
background_opacity   0.92
